services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: inmobiliaria
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./inmobiliaria_api
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./inmobiliaria_api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - SECRET_KEY=changeme
      - DB_NAME=inmobiliaria
      - DB_USER=admin
      - DB_PASSWORD=admin1234
      - DB_HOST=db
      - DB_PORT=5432   

  frontend:
    build:
      context: ./inmobiliaria-front
    ports:
      - "4200:80"
    depends_on:
      - web

volumes:
  postgres_data:
